### ISSUE TITLE
How to get "BotChatSecret" programmatically?

### ISSUE THREAD

**Issue by bora89** [EricDahlvang/TokenBotExample#1]
Can you please tell how to get "BotChatSecret" programmatically? I saw you use something like 
```
            string botChatSecret = ConfigurationManager.AppSettings["BotChatSecret"];
```
in your code. 
I know how to get in in portal.azure.com but we need to get it somehow with API

**Comment by EricDahlvang** [comment]
Hi @bora89 

There is not currently an API to programatically manipulate bots and their settings.  An API is currently being developed, but there is no public timeline available.

In this example, I've simply added the secret to the web.config
